### ISSUE TITLE
Update initial patron check

### ISSUE THREAD

**Issue by austinwbest** [Notifiarr/notifiarr#101]
Currently the client checks if the users is a `subscriber` before allowing the sync to work. This isn't right, it should be checking if they are a `patron` so i have added both to the initial response. `subscriber` and `patron` both of which are a bool

Update the checks to look at the patron t/f instead of subscriber

**Comment by davidnewhall** [comment]
How about I don't check any of that and I just check the counts of `cfsync` and `rpsync`. If > 0, do syncs. You can control sub status on your end.

**Comment by austinwbest** [comment]
No difference to me, however you want to do it :)

**Comment by davidnewhall** [comment]
Just making sure you wont sent positive integers if they're not auth'd to sync.
