### ISSUE TITLE
Manually triggered endpoints

### ISSUE THREAD

**Issue by austinwbest** [Notifiarr/notifiarr#103]
Since many things are on timers, it creates an issue trying to troubleshoot. The sync endpoint is available to be triggered via api & we discussed having all the right click menu options available via endpoint triggers.

This is the request to put it in :)

**Comment by davidnewhall** [comment]
add triggers for snapshot and dashboard

anything else?

**Comment by austinwbest** [comment]
> add triggers for snapshot and dashboard
> 
> anything else?

Services
Plex Sessions
Stuck items

Think that is all of them
