### ISSUE TITLE
Sabnzbd integration 

### ISSUE THREAD

**Issue by 2ndwonder** [Notifiarr/notifiarr#110]
Is it possible to add a Sabnzbd integration? would love to see that

**Comment by austinwbest** [comment]
For the Dashboard..

**Comment by 2ndwonder** [comment]
yes, sorry I forgot to mention that

**Comment by bakerboy448** [comment]
Ref 
- https://sabnzbd.org/wiki/scripts/notification-scripts
- https://github.com/caronc/nzb-notify

Seems it would be more support for nzb-notify than sab specific.

it doesn't appear at a glance they have a generic webhook as far as notifcations goes.

**Comment by austinwbest** [comment]
> Ref
> 
> * https://sabnzbd.org/wiki/scripts/notification-scripts
> * https://github.com/caronc/nzb-notify
> 
> Seems it would be more support for nzb-notify than sab specific.
> 
> it doesn't appear at a glance they have a generic webhook as far as notifcations goes.

He is wanting to see the numbers in the dashboard like deluge/qbt

**Comment by davidnewhall** [comment]
@2ndwonder None of us use this app, and I'll be the one adding the integration (mostly). Please tell me more specifically what data you're like to see so I make sure to grab what seems pertinent to you (as a user of the app).

Ref for me: https://sabnzbd.org/wiki/advanced/api

**Comment by 2ndwonder** [comment]
Queue
Pause
Resume
Speedlimit
Delete

Just the basic stuff like you did with deluge and qbittorrent if possible

Thanks in regard

**Comment by davidnewhall** [comment]
@2ndwonder - My real problem here is that I do not run this app, and even if I install it, I'm honestly not sure how to get it to download stuff so I can pull data and inspect it and write code around it. Do you think you can expose yours to the Internet and share your API key? (privately of course). Then I can just point my client at yours and begin coding it up. If you can give me access for a day or two I should be able to knock this out. I just added another app and it's overall not too much work.

**Comment by 2ndwonder** [comment]
Lucky me hehe thank you

**Comment by davidnewhall** [comment]
New key/object in dashboard payload:
```
 "sabnzbd": [
  {
   "downloaded": 1,
   "downloading": 1,
   "downloads": 3,
   "elapsed": "1.044671023s",
   "error": "",
   "incomplete": 2,
   "instance": 1,
   "latest": [
    {
     "date": "2021-10-17T15:57:37-07:00",
     "name": "5eme.Set.2020.FRENCH.HDRip.x264-EXTREME"
    }
   ],
   "name": "",
   "next": [
    {
     "date": "2022-10-17T16:01:06.488293-07:00",
     "name": "Snapped.S30E01.720p.WEB.h264-BAE"
    },
    {
     "date": "2021-01-17T22:17:00Z",
     "name": "A.Clockwork.Orange.1971.UHD.hdr10.dts.hevc-d3g"
    }
   ],
   "paused": 1,
   "size": 31006227903283
  }
 ]
```
_That seems like a full payload except for `"errors"` which would be a positive integer should one or more exist._

`latest` represents things in history, `next` represents things in queue. The dates associated with them are the finished time and eta, respectively.
