### ISSUE TITLE
rtorrent-flood

### ISSUE THREAD

**Issue by klapvogn** [Notifiarr/notifiarr#118]
I would like to se a intergration of rtorrent-flood, somelike qbittorent, added to the dashboard :-)

**Comment by sbh7600** [comment]
Hi @davidnewhall 

The only thing i have is : https://github.com/jesec/flood

**Comment by davidnewhall** [comment]
Thanks! We'll start there.

**Comment by austinwbest** [comment]
Iirc flood is just a UI wrapper so this is more for rurorrent in general

**Comment by davidnewhall** [comment]
Closing this in favor of #236. Seems more reasonable. @klapvogn If you have an objection, I don't mind entertaining it.
