### ISSUE TITLE
Notifiarr Arch Linux Package

### ISSUE THREAD

**Issue by Jeff254** [Notifiarr/notifiarr#134]
Archlinux has both Official Repositories and Arch User Repositories (AUR). Currently Notifiarr is in neither.

For a Noob, the convertion process is complicated with the potential to brick one's system.

This is a humble request for the Developer to consider availing an Archlinux Package so that we can also access Notifiarr. Thanks in advance.

**Comment by Jeff254** [comment]
Okay, thanks for the great work

**Comment by davidnewhall** [comment]
TODO:
- Check if Travis-CI can build on arch linux. This will allow building a binary package for upload to github.
- Ask @fryfrog (and others) to vet the [PKGBUILD](https://github.com/golift/aur/tree/main/notifiarr) file.
- Look into process for publishing to AUR.

**Comment by davidnewhall** [comment]
I honestly may never do this, but I'm going to leave the issue open in case someone else wants to put time into it. The aur file that builds now seems to work. 🤞 

For now (to anyone that lands here), build a package with `makepkg` using the aur source. Here: https://github.com/golift/aur

**Comment by davidnewhall** [comment]
Soon, Notifiarr will be in the official AUR. Binary packages will also be available for direct download from the GitHub releases page. 

> For a Noob, the convertion process is complicated with the potential to brick one's system.

After installing and using Arch, I've concluded that it's not for noobs. If this statement fits you, use Ubuntu.
