### ISSUE TITLE
Errors on Windows 11 with 0.2.0 and 0.2.1

### ISSUE THREAD

**Issue by azuravian** [Notifiarr/notifiarr#140]
Not sure what happened here as I've been on Windows 11 for a couple of weeks with everything working fine.  Starting yesterday, I get the following error, which is almost identical to one reported earlier in the year:

```
ERROR systray: systray_windows.go:932 Unable to hideMenuItem: Invalid menu handle. [error=Unable to hideMenuItem: %v error_location=github.com/getlantern/systray.hideMenuItem (systray_windows.go:932) error_text=Unable to hideMenuItem: Invalid menu handle. error_type=errors.Error]
ERROR systray: systray_windows.go:932   at github.com/getlantern/systray.hideMenuItem (systray_windows.go:932)
ERROR systray: systray_windows.go:932   at github.com/getlantern/systray.(*MenuItem).Hide (systray.go:190)
ERROR systray: systray_windows.go:932   at github.com/Notifiarr/notifiarr/pkg/client.(*Client).setupMenus (tray.go:69)
ERROR systray: systray_windows.go:932   at github.com/Notifiarr/notifiarr/pkg/client.(*Client).startTray.func1 (tray.go:36)
ERROR systray: systray_windows.go:932   at github.com/getlantern/systray.Register.func2 (systray.go:94)
ERROR systray: systray_windows.go:932   at runtime.goexit (asm_amd64.s:1581)
ERROR systray: systray_windows.go:932 Caused by: Invalid menu handle.
```

This comes up in a Windows Terminal window.  If I close that window, the app closes.  The app sits in the tray, and the menu works.  It is being detected at Notifiarr.com, but functionality does not seem to be working.

**Comment by davidnewhall** [comment]
The error comes from this file:line `(tray.go:69)` which has to do with hiding a menu when debug logs are turned off. Curious if you changed `debug_log` recently? And to what from what? 

More questions:
- Does this happen every time you run the app? 
- Does it seem to happen immediately on startup? 
  - Or does it happen after a period of time? 
  - Or does it seem to happen after a reload?

Thank you for the bug report!

**Comment by azuravian** [comment]
I haven't changed any settings recently.
Happens every time
Immediately on startup

I searched on the discord and found the syntax for debug_log, so I added that in.  This error now doesn't come up, but I get the following:

```[ERROR] 2021/12/04 14:12:25 Sending 2 service updates to Notifiarr, event: start, buffer: 0/1000, error: converting json response: invalid character '<' looking for beginning of value```

The other thing that seems to have changed is that all of this is in an active Terminal window on Windows 11.  I assume this is just supposed to be written to a log, but when I launch the .exe it opens a terminal window and if I close that window, the notifiarr client closes.  When I perform a function in the client menu, I get a notification, but it shows as "Windows Powershell".  

![image](https://user-images.githubusercontent.com/7379812/144721910-2c9689da-ddb7-4d05-8479-061507f2191d.png)

**Comment by azuravian** [comment]
I just have a wealth of errors coming up now.  As part of troubleshooting, I tried to send a test notification.  The website says it was sent, but it doesn't actually do anything in Discord.  When I try to save a notification layout, I get the following:

![image](https://user-images.githubusercontent.com/7379812/144722428-548c925c-aebd-412e-9668-4a7d18bef4ab.png)

**Comment by austinwbest** [comment]
> I just have a wealth of errors coming up now.  As part of troubleshooting, I tried to send a test notification.  The website says it was sent, but it doesn't actually do anything in Discord.  When I try to save a notification layout, I get the following:
> 
> ![image](https://user-images.githubusercontent.com/7379812/144722428-548c925c-aebd-412e-9668-4a7d18bef4ab.png)
> 

That is a site error, hop on discord and we can sort that one out easy enough.

**Comment by davidnewhall** [comment]
I'm pretty sure this is fixed. Please hit me up in Discord if you still get crashes.
