### ISSUE TITLE
[Feature Request] Ombi Integration

### ISSUE THREAD

**Issue by neo-neo1** [Notifiarr/notifiarr#141]
Any plans for Ombi support?

Many can't use Overseerr since no JellyFin support. Ombi also has a bigger user base plus more features such as music.

Thanks for this project.

**Comment by austinwbest** [comment]
> Any plans for Ombi support?
> 
> Many can't use Overseerr since no JellyFin support. Ombi also has a bigger user base plus more features such as music.
> 
> Thanks for this project.

I'm not sure. What kind of support? I don't use it as I use Notifiarr for requests.

**Comment by davidnewhall** [comment]
Notifiarr bot allows doing requests right in your discord channel. There is no web interface, which is the difference for Ombi. Like nitsua asked, what integration would you like to see?

**Comment by davidnewhall** [comment]
If you have some ideas on what an ombi integration would look like, please re-open and let us know!
