### ISSUE TITLE
Check database corruption

### ISSUE THREAD

**Issue by davidnewhall** [Notifiarr/notifiarr#142]
We can presumably check starr app databases and database backups for corruption. Look into this more.

General idea:

    - backup corruption check
        look at the backup location of any configured starr app
        find the newest backup in one of the 3 folders (manual, scheduled, update)
            extract the files
            do an integrity check on the database
            delete the extracted files
            post a webhook of the result with the date/size of the backup
        server will send back the date of the last one sent in startup to avoid checking the same thing if a restart/update happens

    - backup check
        look at the backup location of any configured arr app
        find the newest backup in one of the 3 folders (manual, scheduled, update)
            post a webhook with the date/size of the backup, total backups available on disk and the total size of all backups
        server will send back the date of the last one sent in startup to avoid checking the same thing if a restart/update happens

client may keep track internally which is the newest checked between client restarts as well to avoid checking the same thing

endpoints to trigger these checks
      GET -> /api/backup/corruption
      GET -> /api/backup/status

https://www.sqlite.org/howtocorrupt.html

**Comment by austinwbest** [comment]
Python script while tinkering

```
import sqlite3
import shutil
import os
import stat
import time
from decimal import Decimal, ROUND_UP

RADARR_DATA_DIR = 'C:/ProgramData/Radarr/Backups'
RADARR_TEMP_DIR = RADARR_DATA_DIR +'/corrupt_check'

shutil.unpack_archive(RADARR_DATA_DIR +'/manual/radarr_backup_2020.07.10_18.43.53.zip', RADARR_TEMP_DIR)

try:
    start = time.perf_counter()
    sqliteConnection = sqlite3.connect(RADARR_TEMP_DIR +'/radarr.db')
    cursor = sqliteConnection.cursor()
    print("Database created and connected to SQLite [elapsed: "+ str(Decimal(time.perf_counter() - start).quantize(Decimal('.01'), rounding=ROUND_UP)) +"s]")

    start = time.perf_counter()
    query = "select sqlite_version();"
    cursor.execute(query)
    record = cursor.fetchall()
    print("SQLite database version is: "+ str(record[0]) +" [elapsed: "+ str(Decimal(time.perf_counter() - start).quantize(Decimal('.01'), rounding=ROUND_UP)) +"s]")

    start = time.perf_counter()
    query = "PRAGMA quick_check;"
    cursor.execute(query)
    record = cursor.fetchall()
    print("SQLite quick corruption result is: "+ str(record[0]) +" [elapsed: "+ str(Decimal(time.perf_counter() - start).quantize(Decimal('.01'), rounding=ROUND_UP)) +"s]")

    start = time.perf_counter()
    query = "PRAGMA integrity_check;"
    cursor.execute(query)
    record = cursor.fetchall()
    print("SQLite full corruption result is: "+ str(record[0]) +" [elapsed: "+ str(Decimal(time.perf_counter() - start).quantize(Decimal('.01'), rounding=ROUND_UP)) +"s]")

    cursor.close()

except sqlite3.Error as error:
    print("Error while connecting to sqlite", error)
finally:
    if sqliteConnection:
        sqliteConnection.close()
        print("SQLite connection is closed")

os.chmod(RADARR_TEMP_DIR, stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR)

try:
    shutil.rmtree(RADARR_TEMP_DIR, ignore_errors=False)
except OSError as e:
    print("Error: %s : %s" % (filePath, e.strerror))
```

**Comment by davidnewhall** [comment]
https://github.com/cvilsmeier/sqinn (requires sidecar app)
https://github.com/feyeleanor/serendipity (old af)
https://github.com/alicebob/sqlittle (pure Go, read-only, may not support PRAGMA)
https://pkg.go.dev/modernc.org/sqlite (pure Go, uses a transpiled sqlite3 C lib, **look into this one more**, [source](https://gitlab.com/cznic/sqlite))
