### ISSUE TITLE
Add documentation to README for how Process Service Checks can be configured.

### ISSUE THREAD

**Issue by bakerboy448** [Notifiarr/notifiarr#148]
Title
- doc update
- feature request

Check the systemd status code

---

Add documentation for `process` service checks for windows
Add new feature for \*nix Oses that is similar to the `process` check for windows.

We should check the status of a systemd file and if it is active/running and if it exited unclean (not 0)

**Comment by davidnewhall** [comment]
Re: https://github.com/Notifiarr/notifiarr/pull/58
