### ISSUE TITLE
Request: Add GPU utilization to Plex Session Status

### ISSUE THREAD

**Issue by PearsonFlyer** [Notifiarr/notifiarr#161]
In the Plex session status notifications, CPU and RAM utilization are listed. For those of us who transcode using a GPU, having the GPU utilization listed there as well would be very helpful.

![image](https://user-images.githubusercontent.com/15488393/148706023-2a30db71-bb89-4731-ba75-5aa47ddea159.png)

![image](https://user-images.githubusercontent.com/15488393/148706042-8d74a8d0-91df-4773-93b8-020386c0b87c.png)

**Comment by davidnewhall** [comment]
Nvidia probably not too hard, as long as it's native (not in Docker), but other GPUs may be less friendly. There is nothing out there that's "all-in-one."
