### ISSUE TITLE
Add support for seasonPass endpoint

### ISSUE THREAD

**Issue by austinwbest** [Notifiarr/notifiarr#171]
This is a Sonarr endpoint that allows for mass changing of monitor status on a series/season/episodes

GET - Pulls all series, seasons, etc
POST - Updates a list of series

```
{
    "series": [
        {
            "id": 777,
            "monitored": true
        }
    ],
    "monitoringOptions": {
        "monitor": "all"
    }
}
```

**Comment by davidnewhall** [comment]
I think you mentioned this, and I confirmed it, there is no GET endpoint here. POST is pretty easy. 
Valid values for `monitor` are: 
`all`, `future`, `missing`, `existing`, `firstSeason`, `latestSeason`, and `none`.
