### ISSUE TITLE
Sync failure needs to continue to the next one

### ISSUE THREAD

**Issue by austinwbest** [Notifiarr/notifiarr#219]
If 5 CFs are sent to the client and 1 fails, it doesn't even try to the rest of them.

CF1 - pass
CF2 - pass
CF3 - api fail for who cares why
CF4 - doesnt even try
CF5 - doesnt even try

**Comment by davidnewhall** [comment]
Pretty sure this was fixed in 0.2.7: https://github.com/Notifiarr/notifiarr/releases/tag/v0.2.7

https://github.com/Notifiarr/notifiarr/issues/166

**Comment by davidnewhall** [comment]
I need to see what the failure is on CF3 to know why it's bailing. All the `for` loops in [cfsync.go](https://github.com/Notifiarr/notifiarr/blob/main/pkg/notifiarr/cfsync.go) have `continue` and not `break` on the errors.
