### ISSUE TITLE
Plex Play Trigger can't delete @ people once selected.

### ISSUE THREAD

**Issue by patrick1227** [Notifiarr/notifiarr#227]
On the plex integration page I selected @everyone and myself to get notified. now there is no way to deselect the @everyone notifications

**Comment by davidnewhall** [comment]
ctrl-click it to de-select it.
cmd-click on a mac.

**Comment by patrick1227** [comment]
Thank you I Feel Dumb Now..

**Comment by davidnewhall** [comment]
Took me a sec to figure it out too :P

**Comment by patrick1227** [comment]
Thank you I feel dumb now
