### ISSUE TITLE
Radarr Custom Qualty/Score not shown/Depreciated Webhook

### ISSUE THREAD

**Issue by snupple** [Notifiarr/notifiarr#262]
The notification from Radarr has the Custom Score/Quality Blank when There should be something there:
![2022-07-20_17h15_17](https://user-images.githubusercontent.com/851790/179961622-e7f18cb9-0052-4d08-aed9-c80c02856e33.png)

Also at the bootm it says its using the depreciated Webhook, when its not :)

**Comment by bakerboy448** [comment]
Radarr Develop has this as well
