### ISSUE TITLE
Issues with images pushed to docker hub

### ISSUE THREAD

**Issue by axel-lebourhis** [Notifiarr/notifiarr#266]
Hi !

There's an issue with the latest unstable tag on docker hub, there's only amd64 arch supported, previously it had armv7, which I need for my rpi4.

![image](https://user-images.githubusercontent.com/24732621/180600729-6148d961-8955-481d-81e9-70699067dfb0.png)

I think something's wrong with the way the images are pushed, it happens quite often that some of the arch are not correctly pushed.

**Comment by davidnewhall** [comment]
Hi. Sorry. It's named unstable for a reason. I make no guarantees it's going to be stable. If you're not using amd64 then I recommend sticking to latest.

**Comment by davidnewhall** [comment]
It takes around 20 minutes to build all the architectures. Last night someone came in with an issue, so I made a 1 line changed and rebuilt unstable with 1 arch (takes 2 minutes). It fixed their issue.

I'm rebuilding all the arches now.

**Comment by davidnewhall** [comment]
`main` is also not a bad choice if you need things that `latest` doesn't have, but it's also not a release and not guaranteed to be stable. It should at least contain all arches though since it's always created by the CI pipeline.

**Comment by axel-lebourhis** [comment]
Yeah for sure I mean I don't expect the unstable tag to be... stable :D But I was expecting all the arch to be pushed by some automated system.
If that's what is done with main, then I'll use this one.
By the way, seems your ```latest``` tag is containing only amd64:
![image](https://user-images.githubusercontent.com/24732621/180608420-923968ee-c598-4633-8717-8c665b3e2e8e.png)

That's why I went with ```unstable```/```main``` in the first place.

**Comment by davidnewhall** [comment]
Use `main` for now. The last release was screwed up and didn't make all the architectures because Docker changed how manifests work. I've since fixed it. `unstable` is pushed from my Mac only. `main` is pushed from Travis CI when changes to the main branch occur.

**Comment by davidnewhall** [comment]
Unstable is still building....

**Comment by axel-lebourhis** [comment]
Ok then I'll go with `main` for now ! Will switch to your next `latest` when you release it.
