### ISSUE TITLE
Notifiarr client wont start

### ISSUE THREAD

**Issue by hanses89** [Notifiarr/notifiarr#315]
[INFO] 2022/09/18 07:31:37 🐸 notifiarr v0.4.0-904 Starting! [PID: 1] Sunday, September 18, 2022 @ 7:31:37 AM CEST +0200
[INFO] 2022/09/18 07:31:37 ==> Using Config File: /config/notifiarr.conf
[ERROR] 2022/09/18 07:31:37 Go Panic! This is a bug please report it on github: https://github.com/Notifiarr/notifiarr/issues/new

runtime error: invalid memory address or nil pointer dereference

Suddenly the client wont start. Seems to be after an update. it started approximately 5 hours ago

**Comment by davidnewhall** [comment]
You omitted the stack trace. Please add that. 
ie. the rest of the output when it crashes.

**Comment by davidnewhall** [comment]
pretty please

**Comment by hanses89** [comment]
fixed by going back to the latest tag
