### ISSUE TITLE
fix ui api docs link double //

### ISSUE THREAD

**Issue by bakerboy448** [Notifiarr/notifiarr#350]
https://github.com/Notifiarr/notifiarr/blob/d303ed869f13391a20f7472c3af69b8b341dcbe0/pkg/bindata/templates/landing.html#L26

![image](https://user-images.githubusercontent.com/55419169/197017390-5de8452c-5e3c-4398-82ab-066248254f28.png)

**Comment by davidnewhall** [comment]
https://github.com/Notifiarr/notifiarr/pull/346/files#diff-46de36c8fab038a63d76e32eee76bbb672de1af80c3f3c4890e0e5d39d763274R26
