### ISSUE TITLE
Fix test endpoint.

### ISSUE THREAD

**Issue by davidnewhall** [Notifiarr/notifiarr#399]
Make test endpoint work on notifiarr.com, disable api endpoints on environments.

Fix this:
```
curl https://notifiarr.com/api/v1/notification/test
{ "error": "invalid api key", "incoming": "", "outgoing": "-Key" }
```

Break this:
```
curl https://dev.notifiarr.app/api/v1/notification/test
{
    "code": 200,
    "result": "success",
    "details": {
        "response": "Test payload processed.",
        "started": "2023-01-06T20:14:47+00:00",
        "finished": "2023-01-06T20:14:47+00:00",
        "elapsed": "0s",
        "debug": null
    }
}
```

**Comment by austinwbest** [comment]
We need a way to have a list of endpoints that are "ok" to hit the auth proxy without a server id or apikey

**Comment by davidnewhall** [comment]
```
$ curl https://notifiarr.com/api/v1/notification/test ; echo
{
    "code": 200,
    "result": "success",
    "details": {
        "response": "Test payload processed.",
        "started": "2023-01-28T08:22:11+00:00",
        "finished": "2023-01-28T08:22:11+00:00",
        "elapsed": "0s",
        "debug": null
    }
}
```

**Comment by davidnewhall** [comment]
Disable api on notifiarr.app: https://github.com/Notifiarr/proxyweb/commit/7a91f661f220dba284e7a25ba79dcc6c4750d54c#diff-0d886a336a4d5a47dc33aed0659bed1acfec6220e2bfe505b5ee015d0f6a48f8R12-R15

Allow api on test endpoint:
https://github.com/Notifiarr/proxyweb/commit/7a91f661f220dba284e7a25ba79dcc6c4750d54c#diff-ec9b0b039f7ca35a47b80166f9e5e3259e4cc2efecbfe0740fb21cc8cfde1e37R15-R21
