### ISSUE TITLE
Getting notifiarr tray icon to open with left click

### ISSUE THREAD

**Issue by klepp0906** [Notifiarr/notifiarr#471]
I assume this isnt broken, just not implemented (brand new user so cant be sure).  It was the same way with Jackett until I put in a feature request over there about it.   I imagine most of you guys are linux guys so these things go un-noticed :P  

Hoping to get someone to change it so double left clicking the tray icon opens the webui akin to the rest of the arr suite for us windows users.

**Comment by davidnewhall** [comment]
Isn't a web ui link in the menu? I don't actually think the systray library I use allows me to control the main menu clicks.

**Comment by klepp0906** [comment]
> Isn't a web ui link in the menu? I don't actually think the systray library I use allows me to control the main menu clicks.

it is.  just left click is opening the context menu, as is right click.  the general behavior for windows tray apps is double left click opens them (in this case the webui) and right click would bring up the context menu.

im speaking entirely out of my rear as a non programmer, but i'd like to think it should be possible on the basis that the rest of the arrs and their companion softwares that ive tried do so.  

of course the difference may be that those are installed as opposed to this being ran in a portable fashion.  or perhaps what its written in relative to those.  similar to bazarr being unable to have a tray icon period due to being python.

either way, i'm digressing.  you'd certainly no better than I.  its just what us windows users are used to, and of course would contribute to parity between the rest of the toys :)

**Comment by davidnewhall** [comment]
For some reason I thought one of the systray libraries already had a left/right click split, but I could not find that feature. I will try to work on the [fyne-io variant](https://github.com/fyne-io/systray) to see if we can split left and right click.
