### ISSUE TITLE
NGINX Subdomain Example using SWAG not working

### ISSUE THREAD

**Issue by nothing2obvi** [Notifiarr/notifiarr#481]
Hi there! I used Notifiarr before and loved it but am switching to more of a home lab setup. I am comfortable with LSIO's SWAG container because it is so easy to use and I'm not too literate with that stuff. I tried using the [NGINX subdomain example](https://notifiarr.wiki/en/Client/ReverseProxy#nginx-subdomain-example) for my `notifiarr.subdomain.conf` file, restarted SWAG, and it didn't work. In fact, it made all of my services behind the reverse proxy unreachable until I deleted the`notifiarr.subdomain.conf` file. I also tried [TRaSH's `notifiarr.subdomain.conf` file](https://gist.github.com/TRaSH-/037235b0440b38c8964a2cbb64179cf3) but no luck. I also tried changing the upstreams in the `notifiarr.conf` file to that of my reverse proxy's IP, but nothing happened. I have the Notifiarr UI password enabled if that matters at all.

I'd appreciate any help. Thanks!

**Comment by bakerboy448** [comment]
drop in should work with swag.....going to need the errors from swag and the nginx errors.

also discord is better for support

**Comment by nothing2obvi** [comment]
I'll move over to Discord then and close this issue when solved.

**Comment by nothing2obvi** [comment]
Seems I had to comment out the `X-WebAuth-User` line from the file. Thank you @bakerboy448. I will close this issue.
