### ISSUE TITLE
Request: Integration for Transmission

### ISSUE THREAD

**Issue by DocDrydenn** [Notifiarr/notifiarr#488]
Possible to get an integration for Transmission? 
Data would be similar (if not identical) to what the other torrent client integrations pull.

Web: [https://transmissionbt.com/](https://transmissionbt.com/)
Git: [https://github.com/transmission/transmission](https://github.com/transmission/transmission)

[Available to help and/or test if needed.]

**Comment by viriatusX** [comment]
Yes, please 🙏

**Comment by davidnewhall** [comment]
@mvicari @viriatusX @DocDrydenn 👋 

I need testers. Please join me on the Notifiarr Discord if you have some spare time to help make this a solid integration. We'll get you setup with a test client that can begin sending payloads to the website so @austinwbest can create a Dashboard output. Then we'll need to make sure it all looks beautiful. 🎨

**Comment by davidnewhall** [comment]
This isn't going to get merged or into a release until the upstream library accepts my contribution, or provides another route to input a custom `http.Client`. This feature will remain available in the unstable build for now.
