### ISSUE TITLE
New double click to open webUI simultaneously opens context menu

### ISSUE THREAD

**Issue by klepp0906** [Notifiarr/notifiarr#569]
Was very pleased to see this was added.   Went to give it a test drive just now and while double clicking now does open the webui, each click still opens the context menu at the same time lol.

not sure how many windows user we have so i figured id mention it instead of waiting for someone else to :P

**Comment by davidnewhall** [comment]
Thanks for letting me know! I can probably make the double-click close it. I assume both actions are being called as the clicks happen, and that seems to be the easiest fix. I'll get that into a test build for you to try out soon.

**Comment by davidnewhall** [comment]
On macOS, double-click opens the menu and closes the menu. Both actions seem to cancel the actual double-click. Triple click opens the web page. It's interesting for sure.
