### ISSUE TITLE
Downloader updateCategory and getCategories endpoints

### ISSUE THREAD

**Issue by davidnewhall** [Notifiarr/notifiarr#571]
Add `updateCategory(downloadID)` and `getAllCategories()` API endpoints for all supported downloader applications. 

This is new as we have no API paths for downloaders now.

**Comment by austinwbest** [comment]
I would suggest taking  a look at autobrr as i think they have built a go library for qbt to some extent

**Comment by davidnewhall** [comment]
- **Transmission** can't decide if it's [groups or labels](https://github.com/transmission/transmission/issues/3813), and apparently it's different if you're on Mac vs Linux. Retrieving a list of Groups or Labels is not documented in the [API spec](https://github.com/transmission/transmission/blob/main/docs/rpc-spec.md). Without a list, how do you set a label? And labels do not appear anywhere in the latest version of Transmission on my Mac, so it's rather confusing all around. 
- **rTorrent** also has [no API method](https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html) to return all labels. I do have a method to [set a label](https://github.com/mrobinsn/go-rtorrent/blob/master/rtorrent/rtorrent.go#L446) on a torrent, but how do you get the list? I [asked the library dev](https://github.com/mrobinsn/go-rtorrent/issues/22) if he knows.
- **Qbit** was [easy](https://github.com/golift/qbit/pull/19).
- **Deluge** was [easy](https://github.com/golift/deluge/pull/28).

**Do we need to set labels/categories in NZBGet or SABnzb?**
