### ISSUE TITLE
'ui_password' generator can sometimes add a backslash (\) causing invalid string escape

### ISSUE THREAD

**Issue by SCDevel** [Notifiarr/notifiarr#572]
### Expected Behavior
Generate a password with no errors or crashing

### Actual Behavior
On first startup I got this as my password:
`\AsianStep74`
or
`ui_password = "admin:\AsianStep74"`
now at first glance it looks fine except for the weird backslash

well...

`[ERROR] 2023/08/21 21:20:54 Using Config File: /config/notifiarr.conf: getting config: config file: unmarshaling file /config/notifiarr.conf: toml: line 17 (last key "ui_password"): invalid escape in string '\A'`

### Steps to reproduce

- Reinstall Notifiarr until  it generates you a password
- or just add a backslash to your password...

### Fix
I see two fixes for this

1. If you have control over the generator then disable backslashes...

if you don't have control then the next two options.

2. Search for the backslashes and add a second one `\ -> \\`
this is what I did because I was curious if i would get locked out of the web ui, I did not.
I set the password as `\\AsianStep74` which fixed that crashing and enabled me to login via `\AsianStep74`

3. Search for all backslashes and eliminate them...

PS. Sorry i was bored when writing this so I went all out, and yes that password was actually generated.

**Comment by davidnewhall** [comment]
Thank you for the report! How did you generate the password?

**Comment by SCDevel** [comment]
I believe it was generated with that function that you just patched

**Comment by davidnewhall** [comment]
That's the password you happened to get when you installed? Or you used a function like `--reset`? I just wanted to verify. The bug is new because the password used to get encrypted, but I turned off encryption on the generated password and you're the first to report this bug.

I do appreciate it.

**Comment by SCDevel** [comment]
Ahh sorry on install did not know - - reset was a thing
