### ISSUE TITLE
Password not changing?

### ISSUE THREAD

**Issue by paulr24** [Notifiarr/notifiarr#593]
I must be doing something wrong here but I installed golift/notifiarr:latest via Docker, used my specified credentials to login, but after I change my password via the Notifiarr GUI I find that my password has not changed. Any ideas?

**Comment by davidnewhall** [comment]
What message do you receive when you change your password?

**Comment by paulr24** [comment]
> What message do you receive when you change your password?

It says "Trust Profile Saved. Page will refresh after the reload finishes."

**Comment by davidnewhall** [comment]
Check the log file right after you do that. Any errors?

**Comment by davidnewhall** [comment]
Can you send me a screenshot of the trust profile page? We might get to the bottom of this quicker if you jump on Discord.

**Comment by davidnewhall** [comment]
Please jump on Discord if you still need assistance. Thanks!
