### ISSUE TITLE
Few more endpoints

### ISSUE THREAD

**Issue by austinwbest** [Notifiarr/notifiarr#63]
Radarr
/qualityprofile - GET and returns a JSON payload
/qualityprofile - POST creates a new one with provided JSON payload
/qualityprofile/[id:0-9] - PUT updates an existing with provided JSON payload

Sonarr
/releaseprofile - GET and returns a JSON payload
/releaseprofile - POST creates a new one with provided JSON payload
/releaseprofile/[id:0-9] - PUT updates an existing with provided JSON payload

**Comment by davidnewhall** [comment]
Can you share the json for `releaseprofile`?
