### ISSUE TITLE
Problem with Transmission OpenVPN

### ISSUE THREAD

**Issue by tradenet** [Notifiarr/notifiarr#639]
Is Transmission working? I am getting 409 errors with docker:
transmission-openvpn: image: haugene/transmission-openvpn:latest container_name: transmission-openvpn
`200 OK: <!DOCTYPE html> <html lang="en" xml:lang="en"> <head> <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> <meta http-equiv`

Thanks

**Comment by bakerboy448** [comment]
Need client logs 

that snippet shows a 200 nor a 409?

**Comment by davidnewhall** [comment]
Yes, it works. Click the `i` next to URL and add the required suffix.

**Comment by tradenet** [comment]
> Yes, it works. Click the `i` next to URL and add the required suffix.

Oh ok it's actually "?".
Now I get "state: Unkown ~> OK, output: 409 Conflict 
Which I suppose is the desired result?

**Comment by davidnewhall** [comment]
https://github.com/Notifiarr/notifiarr/pull/536/files#diff-cfb1d7af8cd1eb8446d71eb4726aba844e04467b1e9d916cb9214f25773a3587R303-R306

With a username provided it returns a 401; without a username it returns a 409. These are considered OK. The RPC endpoint does not return a 200 for the service check.
