### ISSUE TITLE
Unraid template

### ISSUE THREAD

**Issue by austinwbest** [Notifiarr/notifiarr#64]
![image](https://user-images.githubusercontent.com/8321115/117077007-5d7f5600-ad05-11eb-8d4d-0861f9ccea99.png)

**Comment by TRaSH-** [comment]
I got a swag .conf file you can use for the reverse proxy

https://gist.github.com/TRaSH-/037235b0440b38c8964a2cbb64179cf3

Line 36 isn't needed if you use a up to date swag and all your conf are up to date

**Comment by zhdenny** [comment]
Unraid Template would of course be nice but this was not terribly difficult to setup.
And super simple Nginx Proxy Manager reverse proxy :)

**Comment by davidnewhall** [comment]
Thanks @TRaSH-! I added a link to that in the repo README in #66.

**Comment by davidnewhall** [comment]
Template added, but we need a new release before it can be merged/used. Pending new feature testing.
