### ISSUE TITLE
Better documentation for the `DN_UI_PASSWORD` env

### ISSUE THREAD

**Issue by sdimovv** [Notifiarr/notifiarr#641]
As far as I understand `DN_UI_PASSWORD` can be used to manage all authentication-related settings (username, password, auth method, auth headers, etc). 

Docs only show how to set a username and password.

**Comment by davidnewhall** [comment]
Only advanced users should avoid using a config file. I don't really want to document how the env variable works because it's not as easy as using a config file, and then folks will ask for help because it's not simple. If you tell me what you want to do, I'll tell you how to do it.

**Comment by sdimovv** [comment]
Oh my... This project is a joke. I asked for this on the Notifiarr Discord first, where "Captain" themselves told me to open this issue here instead.

At the time I opened this I was trying to fix a bug with the Truechart's project Notifiarr chart, which was caused by the lack of documentation on Notifiarr's part.

I have since moved on and am no longer working on this. IMHO no one should be wasting their time with this project. Recyclarr is much easier to set up and free.

In any case you shouldn't be hiding documentation from your users with the pretext of "its for advanced users". You are essentially saying that your users are stupid and none of them are "advanced" enough to be privy of this documentation. 

You can add the docs or not. Doesn't really make a difference to me at this point.

**Comment by davidnewhall** [comment]
k thanks for the update.
