### ISSUE TITLE
Sonarr v4 Stable Cleanup

### ISSUE THREAD

**Issue by bakerboy448** [Notifiarr/notifiarr#648]
- [ ] Remove / depreciate Release Profiles Sync / code cleanup
- [ ] Update UI and Toast messaging - Release Profiles => Custom Formats

**Comment by austinwbest** [comment]
It is only endpoints in the client so they can stay as i know there are future plans to change release profiles and no sense in removing endpoint interaction at this time.

Wording changed and what not can be updated, maybe even just as generic as possible. Radarr/Sonarr sync initiated or something

**Comment by davidnewhall** [comment]
```
github.com/Notifiarr/notifiarr$ git grep -i 'release profiles'
pkg/apps/sonarr.go:// @Description  Removes all Sonarr Release Profiles.
pkg/apps/sonarr.go:// @Summary      Remove Sonarr Release Profiles
pkg/triggers/cfsync/common.go:   TRaSH's custom Radarr formats and Sonarr Release Profiles.
pkg/triggers/cfsync/sonarr.go:          errStr := fmt.Sprintf("getting release profiles: %v ", err)
```

what else?

**Comment by bakerboy448** [comment]
language profiles

**Comment by davidnewhall** [comment]
what am I doing with them?
