### ISSUE TITLE
Add request to client for trash sync

### ISSUE THREAD

**Issue by austinwbest** [Notifiarr/notifiarr#73]
Instead of me running it on a cron, lets switch it to a `GET` request from the client every 10 mins

`https://notifiarr.com/api/v1/user/trash/key-here`

**Comment by davidnewhall** [comment]
On further discussion, we're going to have the client send these payloads instead of a GET:
`customformats` and `getQualityProfiles`

**Comment by davidnewhall** [comment]
Thoughts:
- I do not want to send an API Key in the URL (except for the API Key check). This will cause it to show up in error logs, and I have it well abstracted to use the `X-API-Key` header. Please continue to keep that working.
- Suggest changing the path to contain the app. 
  -  ie. `/api/v1/user/trash/radarr` and `/api/v1/user/trash/sonarr`
