### ISSUE TITLE
Notifiarr won't start if Deluge has empty password

### ISSUE THREAD

**Issue by ocervell** [Notifiarr/notifiarr#742]
My Deluge is only exposed locally and has no password set.

In my configuration I have:
```
[[deluge]]
name     = "deluge"  # Set a name to enable checks of your service.
url      = "http://192.168.1.18:8112"
password = ""
```

Notifiarr fails to start with:
```
[ERROR] 2024/05/28 10:15:55 Using Config File: /config/notifiarr.conf: getting config: setting up app: invalid application configuration provided: missing url or password: Deluge config 1
--
```

This used to work fine but now it fails.

**Comment by davidnewhall** [comment]
Setting a Deluge password will get you fixed right up.

**Comment by ocervell** [comment]
Yes, but I don't want a Deluge password =D My set up is local so it's overkill for me. Is there a way we can accept an empty password ?

**Comment by davidnewhall** [comment]
The Deluge author did not write it so it would work without a password. You're using a modified version. Unfortunately Notifiarr will only work with a password and there's no plans to change that.

**Comment by ocervell** [comment]
Sorry but you are wrong. I'm using the latest official Docker Deluge container and it's definitely possible to set an empty password. Test it out yourself https://hub.docker.com/r/linuxserver/deluge of you don't take my word for it.

On top of that, it used to work with `notifiarr` so it's most likely a recent code change (started after my latest upgrade, probably the first since ~5months) that disabled the possibility (probably something like an if check with the empty string being an empty value)...

**Comment by bakerboy448** [comment]
> The Deluge author did not write it so it would work without a password. You're using a modified version. Unfortunately Notifiarr will only work with a password and there's no plans to change that.

Got confirmation from the deluge team it is possible to set to empty password.

Which is not _no password_

> you CAN set an empty password, but given the fact that we still require you to hit ENTER on a password field i think it demonstrates that it SHOULDNT be set to empty

**Comment by ocervell** [comment]
Right ... So can we allow an empty password by modifying the line [here ](https://github.com/Notifiarr/notifiarr/blob/main/pkg/apps/integrations.go#L98)?

**Comment by davidnewhall** [comment]
How do I give my Deluge _no password_?

**Comment by ocervell** [comment]
There is a slight difference between no password and an empty (`""`) password, we should allow the latest but not the former imo.

**Comment by davidnewhall** [comment]
What's the difference and how would you detect it?

**Comment by bakerboy448** [comment]
None vs. empty string? Is that feasible

**Comment by ocervell** [comment]
Yes. Make it a pointer the &password. If it's nil output an error, otherwise let it go through even if it's "". I've already pointed in the code where the code change needs to be made.

**Comment by davidnewhall** [comment]
![Screenshot 2024-06-13 at 8 44 55 PM](https://github.com/Notifiarr/notifiarr/assets/2402929/a323db3e-8cd0-440c-89f2-61563c1fd0f7)
hmmm
