### ISSUE TITLE
What is this error?

### ISSUE THREAD

**Issue by aryann630** [Notifiarr/notifiarr#755]
[INFO] 2024/06/22 08:32:07  🍄 notifiarr v0.7.3-1852 Starting! [PID: 1] Saturday, June 22, 2024 @ 8:32:07 AM UTC +0000
[INFO] 2024/06/22 08:32:07 ==> Using Config File: /config/notifiarr.conf
[ERROR] 2024/06/22 08:32:07 Go Panic! This is a bug please report it on github: https://github.com/Notifiarr/notifiarr/issues/new
asset: Asset(templates/integrations/qbit.html): Asset templates/integrations/qbit.html can't read by error: read "templates/integrations/qbit.html": gzip: invalid checksum
goroutine 1 [running, locked to thread]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x5e
main.main.func1()
	github.com/Notifiarr/notifiarr/main.go:32 +0x3f
panic({0xec88c0?, 0xc000455d20?})
	runtime/panic.go:770 +0x132
github.com/Notifiarr/notifiarr/pkg/bindata.MustAsset({0x10682f0, 0x20})
	github.com/Notifiarr/notifiarr/pkg/bindata/bindata.go:3225 +0x79
github.com/Notifiarr/notifiarr/pkg/bindata.MustAssetString(...)
	github.com/Notifiarr/notifiarr/pkg/bindata/bindata.go:3234
github.com/Notifiarr/notifiarr/pkg/client.(*Client).ParseGUITemplates(0xc0000d4790)
	github.com/Notifiarr/notifiarr/pkg/client/html_templates.go:352 +0x33f
github.com/Notifiarr/notifiarr/pkg/client.(*Client).loadAssetsTemplates(0xc0000d4790, {0x128ac40, 0xc0000360a0})
	github.com/Notifiarr/notifiarr/pkg/client/html_templates.go:42 +0x3a
github.com/Notifiarr/notifiarr/pkg/client.(*Client).start(0xc0000d4790, {0x128ab60, 0x1e51160})
	github.com/Notifiarr/notifiarr/pkg/client/start.go:161 +0x653
github.com/Notifiarr/notifiarr/pkg/client.Start()
	github.com/Notifiarr/notifiarr/pkg/client/start.go:117 +0xfd
main.main()
	github.com/Notifiarr/notifiarr/main.go:36 +0x7b

**Comment by davidnewhall** [comment]
Best I can tell, that's a damaged docker image. Where'd ya get it?

**Comment by davidnewhall** [comment]
Can you tell me how I can reproduce this?

**Comment by davidnewhall** [comment]
Please re-open if you can provide more info.
