### ISSUE TITLE
Synology HA status (synoha)

### ISSUE THREAD

**Issue by davidnewhall** [Notifiarr/notifiarr#805]
Add these commands' outputs to snapshot for synology:
```
sudo synoha --status
            --local-role
            --local-name
            --lnode-status
            --local-status
            --remote-name
            --remote-role
            --rnode-status
            --remote-status
            --remote-ip
```

Each one has to be run independently. Add sudoers entries on syno from the [installer script](https://github.com/Notifiarr/notifiarr/blob/main/userscripts/install-synology.sh).

**Comment by austinwbest** [comment]
current responses respectively
```
healthy
Active
share-2
share-1: online
share-2: online
share-1
Passive
share-2: online
share-1: online
10.1.0.90
```

I think it is safe to remove `lnode-status` and `rnode-status` as that is also `local-status` & `remote-status` just in reverse. the rest i can make use of between the notification and checking the health for a ping in the notification
