### ISSUE TITLE
No changes to configs

### ISSUE THREAD

**Issue by mcmakar** [Notifiarr/notifiarr#827]
When trying to save changes made in the UI, i get an error 

[gui 'mc' requested] Validating POSTed Config: copying config: encoding config into toml for copying (this is a bug!): template: config:438:24: executing "config" at <.Snapshot.Nvidia.Disabled>: nil pointer evaluating *snapshot.NvidiaConfig.Disabled

Its a known bug? If yes, is there a way of going around it, so i can save the changes? Tried doing [snapshot.nvidia]
disabled = false and true, same error. 

Runs in docker.

**Comment by bakerboy448** [comment]
Known issue; revert back one version for now

**Comment by davidnewhall** [comment]
Is this a new installation, or did the problem begin after upgrading?

**Comment by mcmakar** [comment]
> Is this a new installation, or did the problem begin after upgrading?

A fresh install from the last docker image

**Comment by austinwbest** [comment]
Hopefully the recent 0.8.3 sorts this out

**Comment by davidnewhall** [comment]
@mcmakar Please let us know if you're still experiencing any issue here.
