### ISSUE TITLE
apt command broken on Ubuntu Linux after removing /usr/bin/notifiarr binary

### ISSUE THREAD

**Issue by dwayneem** [Notifiarr/notifiarr#848]
I was advised in the discord server that to uninstall Notifiarr all I had to do was remove the /usr/bin/notifiarr binary.

But after doing so any use of the apt command fails with:
/bin/sh: 1: /usr/bin/notifiarr: not found
Error: Sub-process /usr/bin/notifiarr --apthook returned an error code (127)
Error: Failure running script /usr/bin/notifiarr --apthook

Is there anyway to get download the /usr/bin/notifiarr binary on its own so that I can replace it? "apt install" won't work because of the above problem. Or is there some other way to fix this error? (remove the "apthook"?)

**Comment by austinwbest** [comment]
Should be able to grab the binary from the releases page. I didnt think about the APT hook honestly so maybe just adding the binary back and then doing a typical apt uninstall for the package would remove that hook too. @davidnewhall will know for sure the best way to remove it all (including the hook)

**Comment by dwayneem** [comment]
Thanks. Downloaded the binary from the releases page and did `apt remove notifiarr`
