### ISSUE TITLE
Adjust the conf or the code for bind address

### ISSUE THREAD

**Issue by austinwbest** [Notifiarr/notifiarr#95]
```
## This will be used in Plex for example to send webhooks, Example: http://localhost:5454
## This will be used in Media Requests for example to send payloads, Example: http://your-domain.com:5454
```

If a user actually puts `http://` in the bind address such as the example, it throws...

```
[ERROR] 2021/07/06 14:02:34 Web Server Failed: listen tcp: address http://192.168.1.21:5454: too many colons in address (shutting down)
```

Because that translates to

```
[INFO] 2021/07/06 14:02:34  => Web HTTP Listen: http://http://192.168.1.21:5454/
```

**Comment by davidnewhall** [comment]
> \#\# The ip:port or port to listen on for incoming web requests.

Folks just don't read all the comments?

**Comment by austinwbest** [comment]
> > \#\# The ip:port or port to listen on for incoming web requests.
> 
> Folks just don't read all the comments?

Typically not when there is a full example.. Tends to draw their eyes to it
